[package]
name = "bn-bdash-extras"
version = "0.1.0"
edition = "2024"

[dependencies]
binaryninja = {git = "https://github.com/Vector35/binaryninja-api.git", branch = "dev"}
log = "0.4"
itertools = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
panic = "abort"
build-override.debug = true

[profile.release]
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
